PPLEThai/pple-today

- .changeset/dry-bees-serve.md
- .github/workflows/ci.yaml
> [PPLE-70] CI for expo prebuild

- .changeset/tame-planes-sneeze.md
- .github/workflows/deploy-app.yaml
- .github/workflows/deploy-docker.yaml
- .github/workflows/migrate-database.yaml
- apps-api/backoffice/Dockerfile
- apps-api/backoffice/package.json
- apps-client/backoffice/Dockerfile
- apps-client/backoffice/app/config/clientEnv.ts
- apps-client/backoffice/package.json
- pnpm-lock.yaml
- turbo.json
- Fix CI/CD workflow for backoffice and api
1. Please see result in https://github.com/PPLEThai/pple-today/actions/runs/16538051451
2. Attempt to run workflow and specify path to `miello/fix/ci-cd-actions`
> [!NOTE]
> [PPLE-174] Fix CI/CD workflow for backoffice and api

- .changeset/quiet-mangos-rhyme.md
- apps-api/backoffice/prisma/models/announcement.prisma
- apps-api/backoffice/prisma/models/poll.prisma
- apps-api/backoffice/prisma/models/post.prisma
- apps-api/backoffice/prisma/seed.ts
- apps-api/backoffice/src/dtos/error.ts
- apps-api/backoffice/src/dtos/feed.ts
- apps-api/backoffice/src/dtos/post.ts
- apps-api/backoffice/src/dtos/user.ts
- apps-api/backoffice/src/modules/index.ts
- apps-api/backoffice/src/modules/polls/index.ts
- apps-api/backoffice/src/modules/polls/models.ts
- apps-api/backoffice/src/modules/polls/repository.ts
- apps-api/backoffice/src/modules/polls/services.ts
- Implement poll endpoint for application
- GET `/polls`
- POST `/polls/${id}/vote/${optionId}`
- DELETE `/polls/${id}/vote/${optionId}`
1.
2.
3.
> [!NOTE]
> [PPLE-146] Implement poll endpoint for application

- apps-client/mobile/app/(tabs)/index.tsx
- apps-client/mobile/package.json
- packages/expo-scroll-forwarder/android/src/main/java/expo/modules/scrollforwarder/ExpoScrollForwarderView.kt
- packages/expo-scroll-forwarder/ios/ExpoScrollForwarderView.swift
- pnpm-lock.yaml
The iOS scroll forwarder implementation has a custom UIGestureRecognizer that tries to simulate a scrolling behavior. It is quite good, but doesn't feel right, and I sometimes break when finger mashing the screen.
I've researched a bit, and stumbled on a [stackoverflow post](https://stackoverflow.com/a/75557377) that refers to a WWDC session from 2014 "Advanced Scrollviews and Touch Handling Techniques", which suggests using the scroll view's gesture recognizer in our own view.
Because a `UIGestureRecognizer` can only be used with one view, so by moving it to header, it can only be scrolled by touching the header. This was fixed by moving the whole scrolling view under the scroll forwarder.
https://github.com/user-attachments/assets/4b17d2f4-9a6b-4838-aadd-50066d3c210f
Also thought it'd …
> Improve iOS scroll forwarder

- apps-client/mobile/app/_layout.tsx
- apps-client/mobile/env.ts
> fix: hide dev tools bubbles when local

- .changeset/quick-masks-burn.md
- apps-client/mobile/app/(tabs)/index.tsx
- packages/expo-scroll-forwarder/android/src/main/java/expo/modules/scrollforwarder/ExpoScrollForwarderView.kt
- Implement the Carousel Logic
https://github.com/user-attachments/assets/3fef9415-5e4f-4d3b-b77c-2b2e73942981
https://github.com/user-attachments/assets/7f434c90-65d1-4aaa-a1e8-fba7ead2fba2
1.
2.
3.
> [!NOTE]
> [PPLE-164] Carousel

- .github/workflows/deploy-app.yaml
- .github/workflows/deploy-docker.yaml
- Use matrix strategy to effectively reuse pipeline actions
- Reduce VPN overhead when deploy to server
1.
2.
3.
> [!NOTE]
> [PPLE-235] Improve ci/cd pipeline by using matrix strategy and reduce overhead when deploy

- .changeset/sixty-doors-lay.md
- apps-client/mobile/README.md
- apps-client/mobile/app/(tabs)/index.tsx
- apps-client/mobile/components/announcement.tsx
- integrate announcement to feed
- update readme to be more accurate
https://github.com/user-attachments/assets/9a8f197f-7e36-48bb-a757-c7b322d5372b
> [!NOTE]
> [PPLE-102] Announcement Slide Integrate

- .github/workflows/deploy-app.yaml
> fix: pipeline deployment problem

- .changeset/mighty-eyes-drum.md
- apps-api/backoffice/src/modules/feed/index.ts
- apps-api/backoffice/src/modules/feed/repository.ts
- apps-api/backoffice/src/modules/feed/services.ts
- Change create feed item reaction to upsert with `PUT` request
1. Visit `http://localhost:2000/swagger` and login SSO
2. After that please make request to `http://localhost:2000/feed/:id/reaction`
> [!NOTE]
> [PPLE-273] Change create feed item reaction to upsert

- .changeset/slow-times-return.md
- apps-api/backoffice/Dockerfile
- Fix missing prisma folder from container
1. Please run `docker build -t test -f apps-client/backoffice/Dockerfile .` 
2. Setup environment and start up the container
> [!NOTE]
> [PPLE-290] Missing prisma folder from container

- .changeset/little-tomatoes-shout.md
- apps-client/mobile/app/(tabs)/auth.tsx
- apps-client/mobile/libs/auth/index.ts
- Implement Register to onboarding
https://github.com/user-attachments/assets/e277937b-ceca-4395-a24a-e095e48b8ea6
1.
2.
3.
> [!NOTE]
> feat: register user

- .changeset/forty-dolls-wink.md
- apps-api/backoffice/prisma/migrations/20250901171239_more_constraint_to_address_table/migration.sql
- apps-api/backoffice/prisma/models/address.prisma
- apps-api/backoffice/prisma/models/user.prisma
- apps-api/backoffice/prisma/seed.dev.ts
- apps-api/backoffice/src/modules/profile/repository.ts
- apps-api/backoffice/src/modules/profile/services.ts
- Change data source of thailand address
1.
2.
3.
> [!NOTE]
> [PPLE-293] Change data source of thailand address

- .changeset/old-spies-fold.md
- apps-client/mobile/app/(tabs)/(feed)/index.tsx
- apps-client/mobile/app/(tabs)/profile/index.tsx
- apps-client/mobile/components/pager-with-header.tsx
Pull down to refresh
- feed
- profile setting
https://github.com/user-attachments/assets/e43f1bf3-783f-4283-ace4-4af8d0e58fe9
https://github.com/user-attachments/assets/e7f2f81e-03bc-40e6-ada1-47e54a854d9a
> [!NOTE]
> [PPLE-291] Refresh Feed

- .changeset/itchy-snakes-shout.md
- apps-api/backoffice/src/modules/admin/election/index.ts
- apps-api/backoffice/src/modules/admin/election/models.ts
- apps-api/backoffice/src/modules/admin/election/repository.ts
- apps-api/backoffice/src/modules/admin/election/services.ts
- apps-api/backoffice/src/modules/admin/index.ts
- apps-api/backoffice/src/modules/election/models.ts
- apps-api/backoffice/src/modules/election/services.ts
- packages/api-common/src/dtos/election.ts
- add `GET /admin/elections`
example response:
```json
{
"meta": {
"currentPage": 1,
"totalPage": 1
},
"data": [
{
"id": "hybrid-close-result-announcement",
"name": "hybrid-close-result-announcement",
"description": null,
"location": null,
"type": "HYBRID",
"isCancelled": false,
"encryptionPublicKey": null,
"publishDate": null,
"openRegister": "2025-09-11T11:46:58.756Z",
"closeRegister": "2025-09-12T11:46:58.756Z",
"openVoting": "2025-09-13T11:46:58.756Z",
"closeVoting": "2025-09-14T11:46:58.756Z",
"startResult": "2025-09-15T11:46:58.756Z",
"endResult": "2025-09-16T11:46:58.756Z",
"createdAt": "2025-09-17T11:46:58.938Z",
"updatedAt": "2025-09-17T11:46:58.938Z"
},
{
"id": "hybrid-result-announcement",
"name": "hybrid-result-announcement",
"description": null,
"location": null,
"type": …
```
> [PPLE-316] [API] election dashboard endpoint

- .changeset/chilly-students-tan.md
- apps-client/mobile/app/(tabs)/(feed)/index.tsx
- apps-client/mobile/components/feed/people-card.tsx
https://github.com/user-attachments/assets/79472413-b3c5-418e-b4fb-e9b0b5abc5c7
https://github.com/user-attachments/assets/bff4238e-6eed-4220-9462-847fe5c1b00b
> [!NOTE]
> [PPLE-228] Follow Suggestion UI

- .changeset/smooth-pugs-obey.md
- apps-client/mobile/app/(tabs)/(feed)/index.tsx
- apps-client/mobile/components/feed/people-card.tsx
- apps-client/mobile/components/feed/topic-card.tsx
- apps-client/mobile/components/linear-gradient.tsx
- apps-client/mobile/package.json
- packages/ui/src/components/ui/slide.tsx
- pnpm-lock.yaml
https://github.com/user-attachments/assets/98d3028e-41d3-4e29-b25a-138de7de7b07
1.
2.
3.
> [!NOTE]
> [PPLE-232] Topic Suggestion UI

- .github/workflows/mobile-beta-deployment.yaml
> fix: set environment of mobile beta deployment

- .changeset/unlucky-rats-beg.md
- apps-client/mobile/app/(tabs)/(feed)/topic/suggestion.tsx
- apps-client/mobile/app/(tabs)/(feed)/user-suggestion.tsx
- apps-client/mobile/app/(tabs)/profile/follow.tsx
- apps-client/mobile/components/feed/topic-card.tsx
- apps-client/mobile/components/feed/user-card.tsx
> fix: fix follow suggestion empty state and follow button state

- .changeset/petite-facts-kiss.md
- apps-api/backoffice/src/index.ts
- apps-api/ballot-crypto/src/index.ts
- Fix problem that response is reused when using swagger plugin
1.
2.
3.
> [!NOTE]
> [PPLE-407] Reuse body in swagger plugin
